name = "DataProcessforDQMC"
uuid = "46f08351-ef40-491d-b5bb-ec4458782aec"
authors = ["wangfh5 <wangfohong@126.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
